window.GROWTH_DASHBOARD_DATA = {
  "generatedAt": "2026-06-11T12:41:09Z",
  "source": "Cloudflare Analytics local sync",
  "notes": "Generated by admin/sync_cloudflare.py. Token stays in local environment variables, not in the browser.",
  "traffic": {
    "users": 81,
    "sessions": 1430,
    "pageViews": 1430,
    "returningVisitors": 1349,
    "trafficGrowthPct": -23,
    "engagementGrowthPct": 0,
    "followersDelta": 0
  },
  "topPages": [
    {
      "page": "Homepage",
      "path": "/",
      "views": 80,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/data.js",
      "path": "/data.js",
      "views": 35,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/app.js",
      "path": "/app.js",
      "views": 31,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/cdn-cgi/rum",
      "path": "/cdn-cgi/rum",
      "views": 29,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/assets/world-cup-trophy.png",
      "path": "/assets/world-cup-trophy.png",
      "views": 25,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/style.css",
      "path": "/style.css",
      "views": 25,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/assets/flags/sui.svg",
      "path": "/assets/flags/sui.svg",
      "views": 20,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/assets/players/son-heung-min-stadium.png",
      "path": "/assets/players/son-heung-min-stadium.png",
      "views": 17,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    }
  ],
  "countries": [
    {
      "country": "NL",
      "sessions": 827,
      "engagement": 0
    },
    {
      "country": "SG",
      "sessions": 182,
      "engagement": 0
    },
    {
      "country": "US",
      "sessions": 177,
      "engagement": 0
    },
    {
      "country": "CN",
      "sessions": 144,
      "engagement": 0
    },
    {
      "country": "AD",
      "sessions": 80,
      "engagement": 0
    },
    {
      "country": "CH",
      "sessions": 16,
      "engagement": 0
    },
    {
      "country": "HK",
      "sessions": 12,
      "engagement": 0
    },
    {
      "country": "GB",
      "sessions": 5,
      "engagement": 0
    }
  ],
  "referrers": [
    {
      "source": "Cloudflare 未提供 Referrer",
      "sessions": 1430
    }
  ],
  "posts": []
};
