window.GROWTH_DASHBOARD_DATA = {
  "generatedAt": "2026-06-12T05:33:01Z",
  "source": "Cloudflare Analytics local sync",
  "notes": "Generated by admin/sync_cloudflare.py. Token stays in local environment variables, not in the browser.",
  "traffic": {
    "users": 51,
    "sessions": 1423,
    "pageViews": 1423,
    "returningVisitors": 1372,
    "trafficGrowthPct": 78,
    "engagementGrowthPct": 0,
    "followersDelta": 0
  },
  "hourlyUsers": [
    {
      "time": "10:00",
      "users": 8
    },
    {
      "time": "11:00",
      "users": 1
    },
    {
      "time": "12:00",
      "users": 5
    },
    {
      "time": "13:00",
      "users": 2
    },
    {
      "time": "14:00",
      "users": 7
    },
    {
      "time": "15:00",
      "users": 9
    },
    {
      "time": "16:00",
      "users": 1
    },
    {
      "time": "17:00",
      "users": 1
    },
    {
      "time": "18:00",
      "users": 1
    },
    {
      "time": "19:00",
      "users": 2
    },
    {
      "time": "20:00",
      "users": 1
    },
    {
      "time": "23:00",
      "users": 1
    }
  ],
  "dailyUsers": [
    {
      "date": "06/09",
      "users": 71
    },
    {
      "date": "06/10",
      "users": 184
    },
    {
      "date": "06/11",
      "users": 60
    },
    {
      "date": "06/12",
      "users": 7
    }
  ],
  "topPages": [
    {
      "page": "Homepage",
      "path": "/",
      "views": 62,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/.github",
      "path": "/.github",
      "views": 14,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/LOG.md",
      "path": "/LOG.md",
      "views": 13,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/notifications/*",
      "path": "/notifications/*",
      "views": 13,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/rest/license",
      "path": "/rest/license",
      "views": 13,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/.dockerignore",
      "path": "/.dockerignore",
      "views": 13,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/insta-compose.yml",
      "path": "/insta-compose.yml",
      "views": 12,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    },
    {
      "page": "/test.php",
      "path": "/test.php",
      "views": 12,
      "avgTimeSec": 0,
      "improvement": "Cloudflare request data imported. Add manual qualitative note if this page needs work."
    }
  ],
  "countries": [
    {
      "country": "NL",
      "sessions": 786,
      "engagement": 0
    },
    {
      "country": "SG",
      "sessions": 246,
      "engagement": 0
    },
    {
      "country": "US",
      "sessions": 134,
      "engagement": 0
    },
    {
      "country": "KR",
      "sessions": 127,
      "engagement": 0
    },
    {
      "country": "CN",
      "sessions": 84,
      "engagement": 0
    },
    {
      "country": "HK",
      "sessions": 58,
      "engagement": 0
    },
    {
      "country": "NO",
      "sessions": 13,
      "engagement": 0
    },
    {
      "country": "DE",
      "sessions": 2,
      "engagement": 0
    }
  ],
  "referrers": [
    {
      "source": "Cloudflare 未提供 Referrer",
      "sessions": 1423
    }
  ],
  "health": {
    "score": 0,
    "totalRequests": 1185,
    "okRequests": 633,
    "clientErrorRequests": 552,
    "notFoundRequests": 527,
    "serverErrorRequests": 0,
    "errorRequests": 552,
    "errorRatePct": 46.58,
    "notFoundRatePct": 44.47,
    "serverErrorRatePct": 0.0,
    "statusCodes": [
      {
        "status": 404,
        "requests": 527
      },
      {
        "status": 304,
        "requests": 298
      },
      {
        "status": 200,
        "requests": 221
      },
      {
        "status": 204,
        "requests": 78
      },
      {
        "status": 307,
        "requests": 36
      },
      {
        "status": 403,
        "requests": 19
      },
      {
        "status": 499,
        "requests": 4
      },
      {
        "status": 405,
        "requests": 2
      }
    ],
    "actionable404Requests": 527,
    "suspicious404Requests": 266,
    "actionable404Paths": [
      {
        "path": "/.github",
        "requests": 14
      },
      {
        "path": "/api/env.js",
        "requests": 13
      },
      {
        "path": "/rest/license",
        "requests": 13
      },
      {
        "path": "/notifications/*",
        "requests": 13
      },
      {
        "path": "/LOG.md",
        "requests": 13
      },
      {
        "path": "/.dockerignore",
        "requests": 13
      },
      {
        "path": "/test.php",
        "requests": 12
      },
      {
        "path": "/secrets.yaml",
        "requests": 12
      },
      {
        "path": "/checkout",
        "requests": 12
      },
      {
        "path": "/insta-compose.yml",
        "requests": 12
      }
    ],
    "suspicious404Paths": [
      {
        "path": "/.env.php",
        "requests": 16
      },
      {
        "path": "/.env.live",
        "requests": 15
      },
      {
        "path": "/service/.env",
        "requests": 13
      },
      {
        "path": "/nodeweb/.env",
        "requests": 13
      },
      {
        "path": "/config/common.js",
        "requests": 13
      },
      {
        "path": "/.env-example",
        "requests": 13
      },
      {
        "path": "/config/.env",
        "requests": 13
      },
      {
        "path": "/node/.env",
        "requests": 13
      },
      {
        "path": "/node/backend/.env",
        "requests": 13
      },
      {
        "path": "/wp-json/wp/v2/users",
        "requests": 12
      }
    ],
    "rawTotalRequests": 1451,
    "rawClientErrorRequests": 818,
    "rawErrorRequests": 818,
    "rawNotFoundRequests": 793,
    "actionableErrorRatePct": 46.58
  },
  "posts": []
};
